cc_test(
    name = "tests",
    srcs = ["intersect_spec.cpp"],
    deps = [
        "//set/src:lib",
        "//third_party/googletest:gtest_main",
        "//third_party/googletest:gtest_sample_lib",
    ],
)
