load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "replace_vowel",
    srcs = ["replace_vowel.cpp"],
    hdrs = ["replace_vowel.h"],
    visibility = ["//replace_vowel/test:__pkg__"],
)
