load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "test",
    srcs = ["split_spec.cpp"],
    deps = [
        "//utils/string",
        "@googletest//:gtest_main",
        "@googletest//:gtest_sample_lib",
    ],
)
