cc_test(
    name = "tests",
    srcs = ["replace_vowel_spec.cpp"],
    deps = [
        "//replace_vowel/src:lib",
        "@googletest//:gtest_main",
        "@googletest//:gtest_sample_lib",
    ],
)
