cc_test(
    name = "tests",
    srcs = ["replace_vowel_spec.cpp"],
    deps = [
        "//replace_vowel/src:lib",
        "//third_party/googletest:gtest_main",
        "//third_party/googletest:gtest_sample_lib",
    ],
)
