cc_test(
    name = "tests",
    srcs = ["foo_spec.cpp"],
    deps = [
        "//threads/src:lib",
        "//third_party/googletest:gtest_main",
        "//third_party/googletest:gtest_sample_lib",
    ],
)
