load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "tests",
    srcs = ["test.cpp"],
    deps = [
        "//delete_n_th_repetition",
        "@googletest//:gtest_main",
        "@googletest//:gtest_sample_lib",
    ],
)
