load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "guess_number_game",
    srcs = ["guesser.cpp"],
    hdrs = ["guesser.h"],
    visibility = ["//guess_number_game/test:__pkg__"],
)
