load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "test",
    srcs = [
        "validate_string.cpp",
    ],
    deps = [
        "@googletest//:gtest_main",
        "@googletest//:gtest_sample_lib",
    ],
)