load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "simple_cpp",
    srcs = ["some_class.cpp"],
    hdrs = ["some_class.h"],
    visibility = ["//simple_cpp/test:__pkg__"],
    deps = [],
)
