load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "test",
    srcs = ["test.cpp"],
    deps = [
        "//guess_number_game",
        "@googletest//:gtest_main",
        "@googletest//:gtest_sample_lib",
    ],
)
