cc_test(
    name = "tests",
    srcs = ["test.cpp"],
    deps = [
        "//guess_number_game/src:lib",
        "//third_party/googletest:gtest_main",
        "//third_party/googletest:gtest_sample_lib",
    ],
)
