cc_binary(
    name = "hello-world",
    srcs = ["main.cpp"],
)

cc_library(
    name = "lib",
    srcs = ["delete_n_th.cpp"],
    hdrs = ["delete_n_th.h"],
    visibility = ["//delete_nth_repetition/test:__pkg__"],
)
