load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "string",
    srcs = ["split.cpp"],
    hdrs = ["split.h"],
    visibility = [
        "//utils/string/test:__pkg__",
        "//csv:__pkg__",
        "//pocker:__pkg__",
    ],
)
